'use client'

import Image from 'next/image'
import { useEffect, useState } from 'react'
import { AnimatePresence, motion, useReducedMotion, useScroll, useTransform } from 'framer-motion'
import { ArrowDownRight, ArrowUpRight, Camera, Check, ChevronDown, Compass, Globe2, MapPin, Menu, Phone, Play, Star, X } from 'lucide-react'
import { GOOGLE_MAPS_URL, SOCIAL_LINKS, TRIPADVISOR_URL } from '@/lib/social-links'

const WHATSAPP = '94771234567'
const phone = '+94 77 123 4567'
const faqs = [
  ['When is the best time to visit Udawalawe?', 'Udawalawe is rewarding year-round. The dry season from May to September often brings wildlife closer to water, while the green season brings dramatic landscapes and fewer visitors.'],
  ['How long is a safari?', 'Our standard morning and afternoon drives are around three to four hours. We can shape longer private drives around your route and interests.'],
  ['Can you arrange transfers?', 'Yes. Tell us where you are coming from and we will help coordinate a comfortable transfer to the park gate.'],
  ['Is this suitable for children?', 'Absolutely. We tailor the pace, vehicle and timing for families, with patient naturalist-guided drives and plenty of space to pause.'],
]
const reveal = { hidden: { opacity: 0, y: 28 }, visible: { opacity: 1, y: 0, transition: { duration: .7, ease: 'easeOut' } } }
const stagger = { hidden: {}, visible: { transition: { staggerChildren: .12 } } }

function WhatsAppButton({ label = 'Plan your safari' }: { label?: string }) {
  const message = encodeURIComponent('Hello, I would like to plan a safari in Udawalawe.')
  return <motion.a whileHover={{ y: -3 }} whileTap={{ scale: .98 }} className="button button-bronze" href={`https://wa.me/${WHATSAPP}?text=${message}`} target="_blank" rel="noreferrer">{label}<ArrowUpRight size={16} /></motion.a>
}
function Reveal({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <motion.section className={className} variants={reveal} initial="hidden" whileInView="visible" viewport={{ once: true, amount: .16 }}>{children}</motion.section> }
function Nav({ menuOpen, setMenuOpen }: { menuOpen: boolean; setMenuOpen: (v: boolean) => void }) {
  const [scrolled, setScrolled] = useState(false)
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 30); onScroll(); window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll) }, [])
  return <motion.nav animate={{ backgroundColor: scrolled ? 'rgba(23,35,29,.9)' : 'rgba(23,35,29,0)', backdropFilter: scrolled ? 'blur(14px)' : 'blur(0px)' }} transition={{ duration: .35 }} className="nav"><a className="brand" href="#top" aria-label="Wild Udawalawe home"><span>W</span>ILD<br />UDAWALAWE</a><div className={`nav-links ${menuOpen ? 'open' : ''}`}><a href="#experience" onClick={() => setMenuOpen(false)}>The experience</a><a href="#guide" onClick={() => setMenuOpen(false)}>Park guide</a><a href="#journal" onClick={() => setMenuOpen(false)}>Field notes</a><a href="#contact" onClick={() => setMenuOpen(false)}>Contact</a></div><WhatsAppButton label="Book a drive" /><button className="menu-btn" aria-label={menuOpen ? 'Close menu' : 'Open menu'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></motion.nav>
}

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false); const [openFaq, setOpenFaq] = useState(0); const [sent, setSent] = useState(false); const reduced = useReducedMotion(); const { scrollYProgress } = useScroll(); const heroY = useTransform(scrollYProgress, [0, .3], [0, reduced ? 0 : 80]); const heroScale = useTransform(scrollYProgress, [0, .3], [1, reduced ? 1 : 1.05])
  const localBusinessSchema = { '@context': 'https://schema.org', '@type': 'LocalBusiness', name: 'Wild Udawalawe', description: 'Private safari experiences at the edge of Udawalawe National Park, Sri Lanka.', areaServed: 'Udawalawe National Park, Sri Lanka', sameAs: [SOCIAL_LINKS.facebook, SOCIAL_LINKS.instagram, SOCIAL_LINKS.youtube, SOCIAL_LINKS.tripadvisor] }
  return <main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(localBusinessSchema) }} /><Nav menuOpen={menuOpen} setMenuOpen={setMenuOpen} />
    <section className="hero" id="top"><motion.div className="hero-media" style={{ y: heroY, scale: heroScale }}><Image src="/safari-hero.png" alt="Elephants gathered beside a lake in Udawalawe National Park" fill priority sizes="100vw" className="hero-image" /></motion.div><div className="hero-shade" /><motion.div className="hero-copy" variants={stagger} initial="hidden" animate="visible"><motion.p variants={reveal} className="eyebrow">PRIVATE SAFARI EXPERIENCES · SRI LANKA</motion.p><motion.h1 variants={reveal}>Read the<br /><em>wild</em> closely.</motion.h1><motion.p variants={reveal} className="hero-text">Unhurried days, expert eyes and the quiet thrill of finding elephants in their natural home.</motion.p><motion.div variants={reveal}><WhatsAppButton /></motion.div></motion.div><motion.div className="hero-rating" initial={{ opacity: 0, y: reduced ? 0 : 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .95, duration: .65 }}><span className="hero-rating-mark">◎</span><div><strong>Private by design</strong><small>Locally guided · Unhurried drives</small></div></motion.div><motion.div className="hero-foot" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .8 }}><span>06°26′N 80°53′E</span><span>Udawalawe National Park</span><span>Scroll to explore ↓</span></motion.div></section>
    <Reveal className="statement section-pad"><p className="eyebrow">A DIFFERENT KIND OF GAME DRIVE</p><h2>Not a checklist.<br /><em>A conversation</em><br />with the landscape.</h2><div className="statement-bottom"><p>We are a small, local safari team based at the edge of Udawalawe. Our drives are shaped by the weather, the light and the animals in front of us — never by a fixed route.</p><div className="stats"><div><strong>12+</strong><span>years in the park</span></div><div><strong>01—06</strong><span>guests per jeep</span></div><div><strong>100%</strong><span>locally led</span></div></div></div></Reveal>
    <Reveal className="split-story"><div className="story-image"><Image src="/safari-landscape.png" alt="Safari track through Udawalawe grassland" fill sizes="(max-width: 768px) 100vw, 50vw" /></div><div className="story-copy"><p className="eyebrow">01 / THE PARK</p><h2>Where the dry zone meets the deep green.</h2><p>Udawalawe is one of Sri Lanka’s most reliable places to see wild elephants. Beyond the open plains, its reservoirs, riverine forests and rocky ridges hold an extraordinary cast of birds, reptiles and mammals.</p><a className="text-link" href="#guide">Meet the park <ArrowDownRight size={17} /></a></div></Reveal>
    <Reveal className="experience section-pad" id="experience"><div className="section-heading"><div><p className="eyebrow">02 / THE EXPERIENCE</p><h2>Choose your<br /><em>kind of day.</em></h2></div><p>Every drive is private, flexible and guided by a naturalist who knows these roads as living, changing things.</p></div><motion.div className="experience-grid" variants={stagger}><motion.article variants={reveal} whileHover={{ y: -7 }} className="experience-card card-dark"><span className="card-index">A</span><Compass size={28} strokeWidth={1} /><h3>First light</h3><p>Wake with the park. Cool air, long shadows and the first movement at the waterhole.</p><a href="#contact">Morning drive <ArrowUpRight size={15} /></a></motion.article><motion.article variants={reveal} whileHover={{ y: -7 }} className="experience-card card-photo"><Image src="/safari-elephants.png" alt="Sri Lankan elephant in lush Udawalawe forest" fill sizes="(max-width: 768px) 100vw, 33vw" /><div className="photo-overlay"><span className="card-index">B</span><h3>Golden hour</h3><p>Follow the warmth of the afternoon into a quiet, amber evening.</p></div></motion.article><motion.article variants={reveal} whileHover={{ y: -7 }} className="experience-card card-olive"><span className="card-index">C</span><h3>Full day<br /><em>out there.</em></h3><p>For curious travellers who want more time, more ground and more room for the unexpected.</p><a href="#contact">Build a private day <ArrowUpRight size={15} /></a></motion.article></motion.div></Reveal>
    <Reveal className="quote-band"><p>“The best sightings are not summoned.<br />They are <em>noticed.</em>”</p><span>— OUR FIELD GUIDE</span></Reveal>
    <Reveal className="timeline section-pad" id="journal"><div className="section-heading"><div><p className="eyebrow">03 / A TYPICAL MORNING</p><h2>Let the day<br /><em>unfold.</em></h2></div><p>There is a rhythm to a good safari. We leave space for it.</p></div><div className="timeline-list">{[['05:15', 'The gate opens', 'Coffee, a packed breakfast and the first blue light over the reservoir.'], ['06:30', 'Into the grasslands', 'We follow the signs: fresh tracks, alarm calls, the hush of a watching herd.'], ['09:00', 'Pause & observe', 'No rushing the moment. A shady tree, a thermos poured, stories shared.'], ['11:00', 'Back to base', 'Return with the windows down and the park still unfolding behind you.']].map(([time, title, text]) => <motion.div className="timeline-row" variants={reveal} key={time}><span>{time}</span><div><h3>{title}</h3><p>{text}</p></div><ArrowDownRight size={18} /></motion.div>)}</div></Reveal>
    <Reveal className="guide" id="guide"><div className="guide-inner"><p className="eyebrow">FIELD NOTES / UDAWALAWE</p><h2>A little preparation<br /><em>goes a long way.</em></h2><motion.div className="guide-grid" variants={stagger}>{[['01','Bring layers','Mornings can be cool, afternoons bright. A light layer and sun protection make all the difference.'],['02','Look beyond elephants','Keep watch for painted storks, mugger crocodiles, toque macaques and the flash of a serpent eagle.'],['03','Leave only footprints','We keep a respectful distance, never feed wildlife and carry our waste back out.']].map(([n,t,p]) => <motion.div variants={reveal} key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></motion.div>)}</motion.div></div></Reveal>
    <Reveal className="reviews section-pad"><p className="eyebrow">WHAT TRAVELLERS NOTICE</p><div className="review-content"><div className="stars">★★★★★ <span>Google reviews</span></div><div className="review-actions"><motion.a whileHover={{ y: -3 }} className="button button-dark" href={GOOGLE_MAPS_URL} target="_blank" rel="noopener noreferrer">Google reviews <ArrowUpRight size={16} /></motion.a><motion.a whileHover={{ y: -3 }} className="button button-outline" href={TRIPADVISOR_URL} target="_blank" rel="noopener noreferrer">View on TripAdvisor <ArrowUpRight size={16} /></motion.a></div><blockquote>“A calm, deeply knowledgeable guide. We saw elephants, crocodiles and more birds than we could name — but the real gift was how unhurried the whole morning felt.”</blockquote><p className="reviewer">— Recent guest, United Kingdom</p></div></Reveal>
    <Reveal className="contact-section section-pad" id="contact"><div className="contact-intro"><p className="eyebrow">START A CONVERSATION</p><h2>Tell us what<br /><em>you’re imagining.</em></h2><p>Dates, group size, where you are staying — or simply a feeling. We will come back with honest, useful advice.</p><div className="contact-details"><a href="tel:+94771234567"><Phone size={17} /> {phone}</a><a href={`https://wa.me/${WHATSAPP}`}><span className="wa-dot" /> WhatsApp us directly</a><a href={GOOGLE_MAPS_URL} target="_blank" rel="noopener noreferrer"><MapPin size={17} /> Get directions</a><span>Udawalawe, Sri Lanka</span></div></div><form className="inquiry-form" onSubmit={(e) => { e.preventDefault(); setSent(true) }}><label>Your name<input required name="name" placeholder="How should we call you?" /></label><label>Email address<input required type="email" name="email" placeholder="you@example.com" /></label><label>Tell us a little about your plans<textarea required name="message" rows={4} placeholder="When are you visiting? Who are you travelling with?" /></label><motion.button whileHover={{ y: -3 }} className="button button-dark" type="submit">{sent ? <><Check size={16} /> Thank you — we’ll be in touch</> : <>Send inquiry <ArrowUpRight size={16} /></>}</motion.button></form></Reveal>
    <Reveal className="faq section-pad"><p className="eyebrow">GOOD TO KNOW</p><h2>Questions, <em>answered.</em></h2><div className="faq-list">{faqs.map(([question, answer], i) => <div className="faq-item" key={question}><button onClick={() => setOpenFaq(openFaq === i ? -1 : i)} aria-expanded={openFaq === i}><span>{question}</span><motion.span animate={{ rotate: openFaq === i ? 180 : 0 }}><ChevronDown /></motion.span></button><AnimatePresence initial={false}>{openFaq === i && <motion.div className="faq-answer" initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: .3 }}><p>{answer}</p></motion.div>}</AnimatePresence></div>)}</div></Reveal>
    <Reveal className="final-cta"><p className="eyebrow">THE PARK IS WAITING</p><h2>Go where the<br /><em>quiet begins.</em></h2><WhatsAppButton label="Plan your safari" /></Reveal>
    <footer><a className="brand" href="#top"><span>W</span>ILD UDAWALAWE</a><p>Private safari experiences<br />at the edge of the wild.</p><div className="footer-socials" aria-label="Follow Wild Udawalawe"><a href={SOCIAL_LINKS.facebook} target="_blank" rel="noopener noreferrer" aria-label="Facebook"><Globe2 size={18} /></a><a href={SOCIAL_LINKS.instagram} target="_blank" rel="noopener noreferrer" aria-label="Instagram"><Camera size={18} /></a><a href={SOCIAL_LINKS.youtube} target="_blank" rel="noopener noreferrer" aria-label="YouTube"><Play size={18} /></a><a href={SOCIAL_LINKS.tripadvisor} target="_blank" rel="noopener noreferrer" aria-label="TripAdvisor"><Star size={18} /></a></div><p>© 2026 Wild Udawalawe<br />Sri Lanka</p></footer><motion.div className="mobile-actions" initial={{ y: reduced ? 0 : 80, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: .8, duration: .6 }}><a href={`https://wa.me/${WHATSAPP}`}>WhatsApp</a><a href="tel:+94771234567">Call us</a><a href={GOOGLE_MAPS_URL} target="_blank" rel="noopener noreferrer">Directions</a></motion.div>
  </main>
}
